fixtures:
  repositories:
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    postgresql: "git://github.com/puppetlabs/puppet-postgresql.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    systemd: "git://github.com/camptocamp/puppet-systemd.git"
    selinux: "git://github.com/voxpupuli/puppet-selinux.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    selinux_core:
      repo: https://github.com/puppetlabs/puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
