language: ruby
sudo: false
cache: bundler
notifications:
  email: false
branches:
  only:
    - master
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.1.8
script: "bundle exec rake test"
env:
  - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER=yes
